### ISSUE TITLE
OutOfRangeError when running demo of "inference on image pairs"

### ISSUE THREAD

**Issue by jiaxi-jiang** [philferriere/tfoptflow#19]
Hi, when I try to run the code pwcnet_predict_from_img_pairs.ipynb without any changes using the original data samples on Ubuntu18.04, it has error when I execute` nn = ModelPWCNet(mode='test', options=nn_opts)`. Could someone help me?  Thank you!

![OutOfRangeError](https://user-images.githubusercontent.com/26936848/59285703-b0ae1280-8c6e-11e9-89d6-93ea2009219d.png)

This is the error information:

> Building model...
> 
> WARNING:tensorflow:From /is/sg2/jjiang/tfoptflow/tfoptflow/model_pwcnet.py:1094: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.conv2d instead.
> WARNING:tensorflow:From /is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Colocations handled automatically by placer.
> WARNING:tensorflow:From /is/sg2/jjiang/tfoptflow/tfoptflow/model_pwcnet.py:1221: conv2d_transpose (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.conv2d_transpose instead.
> ... model built.
> Loading model checkpoint ./models/pwcnet-lg-6-2-multisteps-chairsthingsmix/pwcnet.ckpt-595000 for eval or testing...
> 
> WARNING:tensorflow:From /is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
> 
> Instructions for updating:
> 
> Use standard file APIs to check for files with this prefix.
> 
> INFO:tensorflow:Restoring parameters from ./models/pwcnet-lg-6-2-multisteps-chairsthingsmix/pwcnet.ckpt-595000
> 
> ---------------------------------------------------------------------------
> OutOfRangeError                           Traceback (most recent call last)
> ~/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
>    1333     try:
> -> 1334       return fn(*args)
>    1335     except errors.OpError as e:
> 
> ~/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
>    1318       return self._call_tf_sessionrun(
> -> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
>    1320 
> 
> ~/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
>    1406         self._session, options, feed_dict, fetch_list, target_list,
> -> 1407         run_metadata)
>    1408 
> 
> OutOfRangeError: Read less bytes than requested
> 	 [[{{node save/RestoreV2}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> OutOfRangeError                           Traceback (most recent call last)
> <ipython-input-5-914f5cf47659> in <module>
>       1 # Instantiate the model in inference mode and display the model configuration
>       2 # nn = ModelPWCNet(mode='test', options=nn_opts)
> ----> 3 nn = ModelPWCNet(mode='test', options=nn_opts)
> 
> ~/tfoptflow/tfoptflow/model_pwcnet.py in __init__(self, name, mode, session, options, dataset)
>     229             Main results".
>     230         """
> --> 231         super().__init__(name, mode, session, options)
>     232         self.ds = dataset
>     233         # self.adapt_infos = []
> 
> ~/tfoptflow/tfoptflow/model_base.py in __init__(self, name, mode, session, options)
>      64 
>      65             # Build the TF graph
> ---> 66             self.build_graph()
>      67 
>      68     ###
> 
> ~/tfoptflow/tfoptflow/model_base.py in build_graph(self)
>     265         # Init saver (override if you wish) and load checkpoint if it exists
>     266         self.init_saver()
> --> 267         self.load_ckpt()
>     268 
>     269     ###
> 
> ~/tfoptflow/tfoptflow/model_base.py in load_ckpt(self)
>     185             if self.opts['verbose']:
>     186                 print(f"Loading model checkpoint {self.last_ckpt} for eval or testing...\n")
> --> 187             self.saver.restore(self.sess, self.last_ckpt)
>     188             if self.opts['verbose']:
>     189                 print("... model loaded")
> 
> ~/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py in restore(self, sess, save_path)
>    1274       else:
>    1275         sess.run(self.saver_def.restore_op_name,
> -> 1276                  {self.saver_def.filename_tensor_name: save_path})
>    1277     except errors.NotFoundError as err:
>    1278       # There are three common conditions that might cause this error:
> 
> ~/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
>     927     try:
>     928       result = self._run(None, fetches, feed_dict, options_ptr,
> --> 929                          run_metadata_ptr)
>     930       if run_metadata:
>     931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)
> 
> ~/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
>    1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
>    1151       results = self._do_run(handle, final_targets, final_fetches,
> -> 1152                              feed_dict_tensor, options, run_metadata)
>    1153     else:
>    1154       results = []
> 
> ~/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
>    1326     if handle is None:
>    1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
> -> 1328                            run_metadata)
>    1329     else:
>    1330       return self._do_call(_prun_fn, handle, feeds, fetches)
> 
> ~/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
>    1346           pass
>    1347       message = error_interpolation.interpolate(message, self._graph)
> -> 1348       raise type(e)(node_def, op, message)
>    1349 
>    1350   def _extend_graph(self):
> 
> OutOfRangeError: Read less bytes than requested
> 	 [[node save/RestoreV2 (defined at /is/sg2/jjiang/tfoptflow/tfoptflow/model_base.py:119) ]]
> 
> Caused by op 'save/RestoreV2', defined at:
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
>     app.launch_new_instance()
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
>     app.start()
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 505, in start
>     self.io_loop.start()
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 148, in start
>     self.asyncio_loop.run_forever()
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
>     self._run_once()
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
>     handle._run()
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/asyncio/events.py", line 88, in _run
>     self._context.run(self._callback, *self._args)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 690, in <lambda>
>     lambda f: self._run_callback(functools.partial(callback, future))
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
>     ret = callback()
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 781, in inner
>     self.run()
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
>     yielded = self.gen.send(value)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 357, in process_one
>     yield gen.maybe_future(dispatch(*args))
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
>     yielded = next(result)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
>     yield gen.maybe_future(handler(stream, idents, msg))
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
>     yielded = next(result)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
>     user_expressions, allow_stdin,
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
>     yielded = next(result)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
>     res = shell.run_cell(code, store_history=store_history, silent=silent)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
>     return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2848, in run_cell
>     raw_cell, store_history, silent, shell_futures)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2874, in _run_cell
>     return runner(coro)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
>     coro.send(None)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3049, in run_cell_async
>     interactivity=interactivity, compiler=compiler, result=result)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3214, in run_ast_nodes
>     if (yield from self.run_code(code, result)):
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-5-914f5cf47659>", line 3, in <module>
>     nn = ModelPWCNet(mode='test', options=nn_opts)
>   File "/is/sg2/jjiang/tfoptflow/tfoptflow/model_pwcnet.py", line 231, in __init__
>     super().__init__(name, mode, session, options)
>   File "/is/sg2/jjiang/tfoptflow/tfoptflow/model_base.py", line 66, in __init__
>     self.build_graph()
>   File "/is/sg2/jjiang/tfoptflow/tfoptflow/model_base.py", line 266, in build_graph
>     self.init_saver()
>   File "/is/sg2/jjiang/tfoptflow/tfoptflow/model_base.py", line 119, in init_saver
>     self.saver = tf.train.Saver()
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
>     self.build()
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 844, in build
>     self._build(self._filename, build_save=True, build_restore=True)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 881, in _build
>     build_save=build_save, build_restore=build_restore)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
>     restore_sequentially, reshape)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
>     restore_sequentially)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
>     return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
>     name=name)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
>     op_def=op_def)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
>     op_def=op_def)
>   File "/is/sg2/jjiang/Software/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> OutOfRangeError (see above for traceback): Read less bytes than requested
> 	 [[node save/RestoreV2 (defined at /is/sg2/jjiang/tfoptflow/tfoptflow/model_base.py:119) ]]

**Comment by jiaxi-jiang** [comment]
The problem is fixed after I downloaded the newest model file: large multisteps chairsthingsmix...
